apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-microservice
  name: demo-microservice
spec:  
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: demo-microservice
  sessionAffinity: None
  type: LoadBalancer
